### PR TITLE
Bug/date display 24

### PR DESCRIPTION
**Pull request by jwpf100**
Added functionality to fix bug.  Now need to fix tests.

### CODE REVIEW

**Comment by jwpf100** [comment]
I've amended the existing tests so they are expecting the extra property name of DatePostedFormatted.  Do there need to be additional tests to make sure the format is displayed as expected?

**Review by MattGibney — CHANGES_REQUESTED** [review]
This should be much simpler, the `listAllJobs` method in the controller currently passes an array of JobModel objects to the template renderer. This is different to the `viewJob` controller which passes a new object.

If you update the `listAllJobs` controller to return a map of objects, in the same way as the `viewJob` method, you solve the problem without introducing a new data point.

```
async listAllJobs(req, res) {
    const jobs = await req.ModelFactory.job.fetchAllJobs(
      req.ModelFactory,
      req.DaoFactory
    );
    const sortedJobs = jobs.sort(
      (a, b) => b.datePosted.toMillis() - a.datePosted.toMillis()
    );
    return await res.status(200).render('listJobs', {
      jobs: sortedJobs.map((job) => ({
        id: job.id,
        title: job.title,
        location: job.location,
        salary: job.salary,
        jobType: job.jobType,
        description: job.description,
        datePosted: job.datePosted.toFormat('DDD'),
      })),
    });
  },
```

**Review by jwpf100 — COMMENTED** [review]
Made changes to fetchalljobs to use map method and removed changes to models.

**Comment by jwpf100** [comment]
Made changes as requested.

**Review by MattGibney — APPROVED** [review]
Looks good 👍🏻

**Pull request merged**
